spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:mysql://localhost:3306/unicorex_dev
    username: root
    password: ayush@123

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: info

